# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consultation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='consultation.proto',
  package='consultation',
  syntax='proto3',
  serialized_pb=_b('\n\x12\x63onsultation.proto\x12\x0c\x63onsultation\"*\n\rRetortRequest\x12\x19\n\x11original_question\x18\x01 \x01(\t\"\x1d\n\x0bRetortReply\x12\x0e\n\x06retort\x18\x01 \x01(\t2U\n\x0f\x43\x61mpaignManager\x12\x42\n\x06Retort\x12\x1b.consultation.RetortRequest\x1a\x19.consultation.RetortReply\"\x00\x42\x1d\n\x1bnet.yairsovran.consultationb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RETORTREQUEST = _descriptor.Descriptor(
  name='RetortRequest',
  full_name='consultation.RetortRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='original_question', full_name='consultation.RetortRequest.original_question', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=78,
)


_RETORTREPLY = _descriptor.Descriptor(
  name='RetortReply',
  full_name='consultation.RetortReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retort', full_name='consultation.RetortReply.retort', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['RetortRequest'] = _RETORTREQUEST
DESCRIPTOR.message_types_by_name['RetortReply'] = _RETORTREPLY

RetortRequest = _reflection.GeneratedProtocolMessageType('RetortRequest', (_message.Message,), dict(
  DESCRIPTOR = _RETORTREQUEST,
  __module__ = 'consultation_pb2'
  # @@protoc_insertion_point(class_scope:consultation.RetortRequest)
  ))
_sym_db.RegisterMessage(RetortRequest)

RetortReply = _reflection.GeneratedProtocolMessageType('RetortReply', (_message.Message,), dict(
  DESCRIPTOR = _RETORTREPLY,
  __module__ = 'consultation_pb2'
  # @@protoc_insertion_point(class_scope:consultation.RetortReply)
  ))
_sym_db.RegisterMessage(RetortReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033net.yairsovran.consultation'))
import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class CampaignManagerStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Retort = channel.unary_unary(
        '/consultation.CampaignManager/Retort',
        request_serializer=RetortRequest.SerializeToString,
        response_deserializer=RetortReply.FromString,
        )


class CampaignManagerServicer(object):

  def Retort(self, request, context):
    """Gives a randomly chosen evasive answer.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CampaignManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Retort': grpc.unary_unary_rpc_method_handler(
          servicer.Retort,
          request_deserializer=RetortRequest.FromString,
          response_serializer=RetortReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'consultation.CampaignManager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaCampaignManagerServicer(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  def Retort(self, request, context):
    """Gives a randomly chosen evasive answer.
    """
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaCampaignManagerStub(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  def Retort(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    """Gives a randomly chosen evasive answer.
    """
    raise NotImplementedError()
  Retort.future = None


def beta_create_CampaignManager_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_deserializers = {
    ('consultation.CampaignManager', 'Retort'): RetortRequest.FromString,
  }
  response_serializers = {
    ('consultation.CampaignManager', 'Retort'): RetortReply.SerializeToString,
  }
  method_implementations = {
    ('consultation.CampaignManager', 'Retort'): face_utilities.unary_unary_inline(servicer.Retort),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_CampaignManager_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_serializers = {
    ('consultation.CampaignManager', 'Retort'): RetortRequest.SerializeToString,
  }
  response_deserializers = {
    ('consultation.CampaignManager', 'Retort'): RetortReply.FromString,
  }
  cardinalities = {
    'Retort': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'consultation.CampaignManager', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
